
services:
  - type: web
    name: sasb-song-combiner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_song_combiner.py --server.port $PORT --server.enableCORS false
    plan: free
